# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RESTEasy Continues Integration - 5.0

on:
  push:
    branches:
      - '5.0'
    paths-ignore:
      - '.gitignore'
      - '.mvn/**'
      - "docbook/**"
      - "distribution/**"
      - "CONTRIBUTING.md"
      - "License.html"
      - "README.md"
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.gitignore'
      - '.mvn/**'
      - "docbook/**"
      - "distribution/**"
      - "CONTRIBUTING.md"
      - "License.html"
      - "README.md"

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['11', '17']

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }} on WildFly - Linux
        if: runner.os == 'Linux'
        run: |
          mvn clean install -U -B -fae  -Dgithub.actions -Djava8.home="$JAVA_HOME_8_X64"
      - name: Build with Maven Java ${{ matrix.java }} on WildFly - Windows
        if: runner.os == 'Windows'
        run:  |
          mvn clean install -U -B -fae '-Dgithub.actions' '"-Djava8.home=%JAVA_HOME_8_X64%"'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'

  test-with-java8:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Java 11
        run: |
          mvn clean install -U -B -DskipTests
      - name: Test with Java 8 on WildFly - Linux
        if: runner.os == 'Linux'
        run:  |
          mvn clean install -U -B -fae -rf ':resteasy-testsuite' -Dgithub.actions -Dtest.java8.home="$JAVA_HOME_8_X64"
      - name: Test with Java 8 on WildFly - Windows
        if: runner.os == 'Windows'
        run: |
          mvn clean install -U -B -fae -rf ':resteasy-testsuite' '-Dgithub.actions' '"-Dtest.java8.home=%JAVA_HOME_8_X64%"'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/**'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'

  build-java-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Java Docs with Java 11
        run: mvn clean install -U -B -DskipTests '-Dmaven.javadoc.skip=false' javadoc:javadoc

  format-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Validate Formatting
        run: |
          mvn -B validate -Pformat-check -Denforcer.skip=true
