# This workflow is for a nightly run against WildFly upstream

name: WildFly Test Build - 6.2

on:
  push:
    branches:
      - '6.2'
    paths:
      - 'pom.xml'
      - 'providers/**'
      - 'resteasy-bom/**'
      - 'resteasy-cdi/**'
      - 'resteasy-client/**'
      - 'resteasy-client-api/**'
      - 'resteasy-client-utils/**'
      - 'resteasy-core/**'
      - 'resteasy-core-spi/**'
      - 'resteasy-dependencies-bom/**'
      - 'resteasy-feature-pack/**'
      - 'testsuite/arquillian-utils/**'
      - 'testsuite/integration-tests/**'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job and cancel previous ones
concurrency:
  group: '${{ github.ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  wildfly-build:
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build.yml@main
    with:
      wildfly-branch: "main"
      wildfly-repo: "wildfly/wildfly"

  resteasy-build:
    runs-on: ${{ matrix.os }}
    needs: wildfly-build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: ['11', '21']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: wildfly-maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzf wildfly-maven-repository.tar.gz -C ~
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }}
        run: mvn clean install '-Dserver.version=${{needs.wildfly-build.outputs.wildfly-version}}'
      - name: Upload surefire reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/'
      - name: Upload server logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/*.log'

  additional-profiles:
    runs-on: ubuntu-latest
    needs: wildfly-build
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '21']
        profile:
          - '-Dsecurity.manager'
          - '-Dprovision.preview'
          - '-am -Pprovision-without-resteasy,without-jackson,skip-awaiting-upgrade-tests -pl testsuite/integration-tests'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: wildfly-maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzf wildfly-maven-repository.tar.gz -C ~
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Test with ${{ matrix.profile }} - JDK ${{ matrix.java }}
        run:  |
          mvn clean install -U -B -fae ${{ matrix.profile }} '-Dserver.version=${{needs.wildfly-build.outputs.wildfly-version}}'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/surefire-reports/'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/server.log'

  legacy-build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['11', '17']
        wildfly-version: ['28.0.1.Final']

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }} on WildFly ${{ matrix.wildfly-version }} - ${{ matrix.os }}
        run:  |
          mvn clean install -U -B -fae '-Dserver.version=${{ matrix.wildfly-version }}' '-Dgithub.actions'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/surefire-reports/'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/server.log'
